spring.application.name=TodoBackend
spring.datasource.url=jdbc:postgresql://localhost:5432/tododb
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update